pub mod analyzer;
pub mod config;
pub mod discovery;
pub mod emit;
pub mod error;
pub mod migrations;
pub mod model;
pub mod reset;
pub mod schema;
pub mod seeds;
mod sql_files;
pub mod sql_text;
pub mod sqlite;
pub mod views;

pub use analyzer::{analyze_project, analyze_project_with_init_sql};
pub use config::{Config, FileConfig, Target};
pub use discovery::discover_sql_files;
pub use emit::emit_project;
pub use error::{Error, Result};
