use std::collections::BTreeMap;
use std::fs;

use heck::ToPascalCase;

use crate::config::Config;
use crate::error::{Error, Result};
use crate::model::{Project, Query, ReturnType};

pub fn emit(config: &Config, project: &Project) -> Result<()> {
    let mut by_module: BTreeMap<&str, Vec<&Query>> = BTreeMap::new();
    for query in &project.queries {
        by_module.entry(&query.module_name).or_default().push(query);
    }

    fs::create_dir_all(&config.output).map_err(|source| Error::CreateDir {
        path: config.output.clone(),
        source,
    })?;

    let modules = by_module.keys().copied().collect::<Vec<_>>();

    for (module, queries) in by_module {
        let path = config.output.join(format!("{module}.rs"));
        let content = render_module(queries);
        if config.check {
            let current = fs::read_to_string(&path).map_err(|source| Error::ReadFile {
                path: path.clone(),
                source,
            })?;
            if current != content {
                return Err(Error::StaleGeneratedFile { path });
            }
            continue;
        }
        fs::write(&path, content).map_err(|source| Error::WriteFile {
            path: path.clone(),
            source,
        })?;
    }

    emit_mod_rs(config, modules)
}

fn emit_mod_rs(config: &Config, modules: Vec<&str>) -> Result<()> {
    let path = config.output.join("mod.rs");
    let content = modules
        .into_iter()
        .map(|module| format!("pub mod {module};\n"))
        .collect::<String>();

    if config.check {
        let current = fs::read_to_string(&path).map_err(|source| Error::ReadFile {
            path: path.clone(),
            source,
        })?;
        if current != content {
            return Err(Error::StaleGeneratedFile { path });
        }
        return Ok(());
    }

    fs::write(&path, content).map_err(|source| Error::WriteFile {
        path: path.clone(),
        source,
    })
}

fn render_module(queries: Vec<&Query>) -> String {
    let mut output = String::from(
        "// This file is generated by Marmot. Do not edit by hand.\n\
         #![allow(dead_code)]\n\
         use rusqlite::{named_params, Connection, Result};\n\n",
    );

    for query in queries {
        output.push_str(&render_query(query));
        output.push('\n');
    }

    output
}

fn render_query(query: &Query) -> String {
    let const_name = format!("{}_SQL", query.name.to_uppercase());
    let sql = raw_string(&query.sql);

    let mut output = format!("const {const_name}: &str = {sql};\n\n");
    match &query.return_type {
        ReturnType::Execute => output.push_str(&render_execute(query, &const_name)),
        ReturnType::Rows { .. } if query.columns.len() == 1 => {
            output.push_str(&render_scalar_select(query, &const_name))
        }
        ReturnType::Rows { .. } => output.push_str(&render_select(query, &const_name)),
    }
    output
}

fn render_select(query: &Query, const_name: &str) -> String {
    let ReturnType::Rows { row_type } = &query.return_type else {
        unreachable!("render_select only accepts row queries")
    };
    let row_type = row_type
        .clone()
        .unwrap_or_else(|| format!("{}Row", query.name.to_pascal_case()));
    let fields = query
        .columns
        .iter()
        .map(|column| format!("    pub {}: {},\n", column.field_name, column.rust_type()))
        .collect::<String>();
    let params = render_params(query);
    let named_params = render_named_params(query);
    let row_fields = query
        .columns
        .iter()
        .enumerate()
        .map(|(index, column)| format!("            {}: row.get({index})?,\n", column.field_name))
        .collect::<String>();

    format!(
        "#[derive(Debug, Clone, PartialEq)]\n\
         pub struct {row_type} {{\n{fields}}}\n\n\
         pub fn {name}(conn: &Connection{params}) -> Result<Vec<{row_type}>> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             let rows = stmt.query_map({named_params}, |row| {{\n\
                 Ok({row_type} {{\n{row_fields}        }})\n\
             }})?;\n\
             rows.collect()\n\
         }}\n",
        name = query.name
    )
}

fn render_scalar_select(query: &Query, const_name: &str) -> String {
    let rust_type = query.columns[0].rust_type();
    let params = render_params(query);
    let named_params = render_named_params(query);
    format!(
        "pub fn {name}(conn: &Connection{params}) -> Result<Vec<{rust_type}>> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             let rows = stmt.query_map({named_params}, |row| row.get(0))?;\n\
             rows.collect()\n\
         }}\n\n\
         pub fn {name}_one(conn: &Connection{params}) -> Result<{rust_type}> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             stmt.query_row({named_params}, |row| row.get(0))\n\
         }}\n",
        name = query.name
    )
}

fn render_execute(query: &Query, const_name: &str) -> String {
    let params = render_params(query);
    let named_params = render_named_params(query);
    format!(
        "pub fn {name}(conn: &Connection{params}) -> Result<usize> {{\n\
             conn.execute({const_name}, {named_params})\n\
         }}\n",
        name = query.name
    )
}

fn render_params(query: &Query) -> String {
    query
        .parameters
        .iter()
        .map(|param| format!(", {}: impl rusqlite::ToSql", param.name))
        .collect()
}

fn render_named_params(query: &Query) -> String {
    if query.parameters.is_empty() {
        return "[]".to_string();
    }

    let pairs = query
        .parameters
        .iter()
        .flat_map(|param| {
            param
                .sql_names
                .iter()
                .map(|sql_name| format!("{sql_name:?}: {}", param.name))
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("named_params! {{ {pairs} }}")
}

fn raw_string(value: &str) -> String {
    for hashes in 0..8 {
        let marker = "#".repeat(hashes);
        let terminator = format!("\"{marker}");
        if !value.contains(&terminator) {
            return format!("r{marker}\"{value}\"{marker}");
        }
    }
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Parameter, Query};
    use std::path::PathBuf;

    #[test]
    fn render_named_params_preserves_sql_placeholder_prefixes() {
        let query = Query {
            source_path: PathBuf::from("src/posts/sql/search.sql"),
            module_name: "posts_sql".to_string(),
            name: "search".to_string(),
            return_type: ReturnType::Execute,
            sql: "update posts set viewed = 1 where user_id = @user_id and created_at >= :since and title like $pattern or owner_id = :user_id".to_string(),
            parameters: vec![
                Parameter {
                    name: "user_id".to_string(),
                    sql_names: vec!["@user_id".to_string(), ":user_id".to_string()],
                },
                Parameter {
                    name: "since".to_string(),
                    sql_names: vec![":since".to_string()],
                },
                Parameter {
                    name: "pattern".to_string(),
                    sql_names: vec!["$pattern".to_string()],
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query);

        assert!(output.contains("\"@user_id\": user_id"));
        assert!(output.contains("\":user_id\": user_id"));
        assert!(output.contains("\":since\": since"));
        assert!(output.contains("\"$pattern\": pattern"));
    }
}
