use std::collections::{BTreeMap, BTreeSet};
use std::fs;

use heck::ToPascalCase;

use crate::config::Config;
use crate::error::{Error, Result};
use crate::model::{Project, Query, ReturnType};

pub fn emit(config: &Config, project: &Project) -> Result<()> {
    let mut by_module: BTreeMap<&str, Vec<&Query>> = BTreeMap::new();
    for query in &project.queries {
        by_module.entry(&query.module_name).or_default().push(query);
    }

    fs::create_dir_all(&config.output).map_err(|source| Error::CreateDir {
        path: config.output.clone(),
        source,
    })?;

    let modules = by_module.keys().copied().collect::<Vec<_>>();

    for (module, queries) in by_module {
        let path = config.output.join(format!("{module}.rs"));
        let content = render_module(queries)?;
        if config.check {
            ensure_file_current(&path, &content)?;
            continue;
        }
        fs::write(&path, content).map_err(|source| Error::WriteFile {
            path: path.clone(),
            source,
        })?;
    }

    emit_mod_rs(config, modules)
}

fn emit_mod_rs(config: &Config, modules: Vec<&str>) -> Result<()> {
    let path = config.output.join("mod.rs");
    let content = modules
        .into_iter()
        .map(|module| format!("pub mod {module};\n"))
        .collect::<String>();

    if config.check {
        ensure_file_current(&path, &content)?;
        return Ok(());
    }

    fs::write(&path, content).map_err(|source| Error::WriteFile {
        path: path.clone(),
        source,
    })
}

fn ensure_file_current(path: &std::path::Path, content: &str) -> Result<()> {
    match fs::read_to_string(path) {
        Ok(current) if current == content => Ok(()),
        Ok(_) => Err(Error::StaleGeneratedFile {
            path: path.to_path_buf(),
        }),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
            Err(Error::StaleGeneratedFile {
                path: path.to_path_buf(),
            })
        }
        Err(source) => Err(Error::ReadFile {
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn render_module(queries: Vec<&Query>) -> Result<String> {
    validate_generated_names(&queries)?;
    validate_shared_row_types(&queries)?;
    validate_parameter_styles(&queries)?;
    let import_macros = render_import_macros(&queries);
    let mut output = format!(
        "// This file is generated by Marmot. Do not edit by hand.\n\
         #![allow(dead_code)]\n\
         use rusqlite::{{{import_macros}Connection, Result}};\n\n",
    );
    let mut emitted_row_types = BTreeSet::new();

    for query in queries {
        let include_row_struct = match &query.return_type {
            ReturnType::Rows {
                row_type: Some(row_type),
            } if query.columns.len() > 1 => emitted_row_types.insert(row_type.clone()),
            _ => true,
        };
        output.push_str(&render_query(query, include_row_struct));
        output.push('\n');
    }

    Ok(output)
}

fn validate_generated_names(queries: &[&Query]) -> Result<()> {
    let mut generated_function_names = BTreeSet::new();
    let mut duplicate_query_names = BTreeSet::new();
    for query in queries {
        for generated_name in generated_function_names_for(query) {
            if !generated_function_names.insert(generated_name.clone()) {
                duplicate_query_names.insert(generated_name);
            }
        }
    }
    if !duplicate_query_names.is_empty() {
        return Err(Error::DuplicateQueryNames {
            names: duplicate_query_names.into_iter().collect(),
        });
    }

    let mut shared_row_types: BTreeSet<String> = BTreeSet::new();
    let mut emitted_row_types: BTreeSet<String> = BTreeSet::new();
    let mut duplicate_row_types = BTreeSet::new();

    for query in queries {
        let ReturnType::Rows { row_type } = &query.return_type else {
            continue;
        };
        if query.columns.len() <= 1 {
            continue;
        }

        let row_type = match row_type {
            Some(row_type) => {
                if shared_row_types.insert(row_type.clone())
                    && !emitted_row_types.insert(row_type.clone())
                {
                    duplicate_row_types.insert(row_type.clone());
                }
                continue;
            }
            None => format!("{}Row", query.name.to_pascal_case()),
        };

        if !emitted_row_types.insert(row_type.clone()) {
            duplicate_row_types.insert(row_type);
        }
    }

    if !duplicate_row_types.is_empty() {
        return Err(Error::DuplicateRowTypeNames {
            names: duplicate_row_types.into_iter().collect(),
        });
    }

    Ok(())
}

fn validate_parameter_styles(queries: &[&Query]) -> Result<()> {
    for query in queries {
        let has_anonymous = query
            .parameters
            .iter()
            .any(|param| param.sql_names.is_empty());
        let has_named = query
            .parameters
            .iter()
            .flat_map(|param| &param.sql_names)
            .any(|sql_name| !sql_name.starts_with('?'));
        let has_numbered = query
            .parameters
            .iter()
            .flat_map(|param| &param.sql_names)
            .any(|sql_name| sql_name.starts_with('?'));
        if has_anonymous && (has_named || (has_numbered && !can_render_as_positional(query))) {
            return Err(Error::MixedParameterStyles {
                path: query.source_path.clone(),
            });
        }
    }

    Ok(())
}

fn can_render_as_positional(query: &Query) -> bool {
    if query.parameters.is_empty() {
        return false;
    }
    if query
        .parameters
        .iter()
        .all(|param| param.sql_names.is_empty())
    {
        return true;
    }
    if query.parameters.iter().any(|param| {
        param
            .sql_names
            .iter()
            .any(|sql_name| !sql_name.starts_with('?'))
    }) {
        return false;
    }

    let mut slots = query
        .parameters
        .iter()
        .filter_map(parameter_positional_slot)
        .collect::<Vec<_>>();
    slots.sort_unstable();

    slots.iter().copied().eq(1..=query.parameters.len())
}

fn parameter_positional_slot(param: &crate::model::Parameter) -> Option<usize> {
    param
        .sql_names
        .iter()
        .filter_map(|sql_name| {
            sql_name
                .strip_prefix('?')
                .and_then(|number| number.parse::<usize>().ok())
        })
        .min()
        .or_else(|| anonymous_parameter_slot(&param.name))
}

fn anonymous_parameter_slot(name: &str) -> Option<usize> {
    if name == "param" {
        return Some(1);
    }

    name.strip_prefix("param_")
        .and_then(|number| number.parse::<usize>().ok())
}

fn generated_function_names_for(query: &Query) -> Vec<String> {
    let mut names = vec![query.name.clone()];
    if matches!(query.return_type, ReturnType::Rows { .. }) && query.columns.len() == 1 {
        names.push(format!("{}_one", query.name));
    }
    names
}

fn render_import_macros(queries: &[&Query]) -> String {
    let uses_named = queries.iter().any(|query| {
        !can_render_as_positional(query)
            && query
                .parameters
                .iter()
                .any(|param| !param.sql_names.is_empty())
    });
    let uses_positional = queries.iter().any(|query| can_render_as_positional(query));
    let mut imports = Vec::new();
    if uses_named {
        imports.push("named_params");
    }
    if uses_positional {
        imports.push("params");
    }

    if imports.is_empty() {
        String::new()
    } else {
        format!("{}, ", imports.join(", "))
    }
}
fn validate_shared_row_types(queries: &[&Query]) -> Result<()> {
    let mut shared_rows: BTreeMap<&str, &Query> = BTreeMap::new();
    for query in queries {
        let ReturnType::Rows {
            row_type: Some(row_type),
        } = &query.return_type
        else {
            continue;
        };

        if let Some(existing_query) = shared_rows.get(row_type.as_str()) {
            if existing_query.columns != query.columns {
                return Err(Error::SharedRowTypeMismatch {
                    row_type: row_type.clone(),
                    paths: vec![
                        existing_query.source_path.clone(),
                        query.source_path.clone(),
                    ],
                });
            }
        } else {
            shared_rows.insert(row_type, query);
        }
    }

    Ok(())
}

fn render_query(query: &Query, include_row_struct: bool) -> String {
    let const_name = format!("{}_SQL", query.name.to_uppercase());
    let sql = raw_string(&query.sql);

    let mut output = format!("const {const_name}: &str = {sql};\n\n");
    match &query.return_type {
        ReturnType::Execute => output.push_str(&render_execute(query, &const_name)),
        ReturnType::Rows { .. } if query.columns.len() == 1 => {
            output.push_str(&render_scalar_select(query, &const_name))
        }
        ReturnType::Rows { .. } => {
            output.push_str(&render_select(query, &const_name, include_row_struct))
        }
    }
    output
}

fn render_select(query: &Query, const_name: &str, include_row_struct: bool) -> String {
    let ReturnType::Rows { row_type } = &query.return_type else {
        unreachable!("render_select only accepts row queries")
    };
    let row_type = row_type
        .clone()
        .unwrap_or_else(|| format!("{}Row", query.name.to_pascal_case()));
    let fields = query
        .columns
        .iter()
        .map(|column| format!("    pub {}: {},\n", column.field_name, column.rust_type()))
        .collect::<String>();
    let params = render_params(query);
    let named_params = render_named_params(query);
    let row_fields = query
        .columns
        .iter()
        .enumerate()
        .map(|(index, column)| format!("            {}: row.get({index})?,\n", column.field_name))
        .collect::<String>();

    let struct_definition = if include_row_struct {
        format!(
            "#[derive(Debug, Clone, PartialEq)]\n\
             pub struct {row_type} {{\n{fields}}}\n\n"
        )
    } else {
        String::new()
    };

    format!(
        "{struct_definition}\
         pub fn {name}(conn: &Connection{params}) -> Result<Vec<{row_type}>> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             let rows = stmt.query_map({named_params}, |row| {{\n\
                 Ok({row_type} {{\n{row_fields}        }})\n\
             }})?;\n\
             rows.collect()\n\
         }}\n",
        name = query.name
    )
}

fn render_scalar_select(query: &Query, const_name: &str) -> String {
    let rust_type = query.columns[0].rust_type();
    let params = render_params(query);
    let named_params = render_named_params(query);
    format!(
        "pub fn {name}(conn: &Connection{params}) -> Result<Vec<{rust_type}>> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             let rows = stmt.query_map({named_params}, |row| row.get(0))?;\n\
             rows.collect()\n\
         }}\n\n\
         pub fn {name}_one(conn: &Connection{params}) -> Result<{rust_type}> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             stmt.query_row({named_params}, |row| row.get(0))\n\
         }}\n",
        name = query.name
    )
}

fn render_execute(query: &Query, const_name: &str) -> String {
    let params = render_params(query);
    let named_params = render_named_params(query);
    format!(
        "pub fn {name}(conn: &Connection{params}) -> Result<usize> {{\n\
             conn.execute({const_name}, {named_params})\n\
         }}\n",
        name = query.name
    )
}

fn render_params(query: &Query) -> String {
    let mut params = query.parameters.iter().collect::<Vec<_>>();
    if query
        .parameters
        .iter()
        .any(|param| !param.sql_names.is_empty())
        && can_render_as_positional(query)
    {
        params.sort_by_key(|param| parameter_positional_slot(param).unwrap_or(usize::MAX));
    }
    params
        .into_iter()
        .map(|param| format!(", {}: {}", param.name, param.rust_argument_type()))
        .collect()
}

fn render_named_params(query: &Query) -> String {
    if query.parameters.is_empty() {
        return "[]".to_string();
    }

    if can_render_as_positional(query) {
        let mut params = query.parameters.iter().collect::<Vec<_>>();
        if query
            .parameters
            .iter()
            .any(|param| !param.sql_names.is_empty())
        {
            params.sort_by_key(|param| parameter_positional_slot(param).unwrap_or(usize::MAX));
        }
        let names = params
            .iter()
            .map(|param| param_binding_expr(param))
            .collect::<Vec<_>>()
            .join(", ");
        return format!("params![{names}]");
    }

    let pairs = query
        .parameters
        .iter()
        .flat_map(|param| {
            param
                .sql_names
                .iter()
                .map(|sql_name| format!("{sql_name:?}: {}", param_binding_expr(param)))
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("named_params! {{ {pairs} }}")
}

fn param_binding_expr(param: &crate::model::Parameter) -> String {
    if !param.nullable
        && matches!(
            param.column_type,
            crate::model::ValueType::String | crate::model::ValueType::Bytes
        )
    {
        format!("{}.as_ref()", param.name)
    } else {
        param.name.clone()
    }
}

fn raw_string(value: &str) -> String {
    for hashes in 0..8 {
        let marker = "#".repeat(hashes);
        let terminator = format!("\"{marker}");
        if !value.contains(&terminator) {
            return format!("r{marker}\"{value}\"{marker}");
        }
    }
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Column, Parameter, Query, ValueType};
    use std::path::PathBuf;

    #[test]
    fn render_named_params_preserves_sql_placeholder_prefixes() {
        let query = Query {
            source_path: PathBuf::from("src/posts/sql/search.sql"),
            module_name: "posts_sql".to_string(),
            name: "search".to_string(),
            return_type: ReturnType::Execute,
            sql: "update posts set viewed = 1 where user_id = @user_id and created_at >= :since and title like $pattern or owner_id = :user_id".to_string(),
            parameters: vec![
                Parameter {
                    name: "user_id".to_string(),
                    sql_names: vec!["@user_id".to_string(), ":user_id".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "since".to_string(),
                    sql_names: vec![":since".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "pattern".to_string(),
                    sql_names: vec!["$pattern".to_string()],
                    column_type: ValueType::String,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query, true);

        assert!(output.contains("\"@user_id\": user_id"));
        assert!(output.contains("\":user_id\": user_id"));
        assert!(output.contains("\":since\": since"));
        assert!(output.contains("\"$pattern\": pattern.as_ref()"));
    }

    #[test]
    fn render_positional_params_uses_params_macro() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ? where id = ?".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
                Parameter {
                    name: "param_2".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query, true);

        assert!(output.contains("params![param.as_ref(), param_2]"));
    }

    #[test]
    fn render_dense_numbered_params_positionally() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ?2 where id = ?1 or parent_id = ?1".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec!["?1".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "param_2".to_string(),
                    sql_names: vec!["?2".to_string()],
                    column_type: ValueType::String,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query, true);

        assert!(output.contains("params![param, param_2.as_ref()]"));
    }

    #[test]
    fn render_sparse_numbered_params_uses_sqlite_parameter_names() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ?2".to_string(),
            parameters: vec![Parameter {
                name: "param_2".to_string(),
                sql_names: vec!["?2".to_string()],
                column_type: ValueType::String,
                nullable: false,
            }],
            columns: vec![],
        };

        let output = render_query(&query, true);

        assert!(output.contains("named_params! { \"?2\": param_2.as_ref() }"));
    }

    #[test]
    fn render_dense_mixed_numbered_and_anonymous_params_positionally() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "delete from users where id = ?1 and name = ?".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec!["?1".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "param_2".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_module(vec![&query]).unwrap();

        assert!(output.contains("params![param, param_2.as_ref()]"));
    }

    #[test]
    fn render_module_rejects_anonymous_mixed_with_named_parameters() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ? where id = @id".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
                Parameter {
                    name: "id".to_string(),
                    sql_names: vec!["@id".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        assert!(matches!(
            render_module(vec![&query]),
            Err(Error::MixedParameterStyles { path }) if path == PathBuf::from("src/users/sql/find.sql")
        ));
    }

    #[test]
    fn render_module_rejects_anonymous_mixed_with_numbered_parameters() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ? where id = ?1".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
                Parameter {
                    name: "param_1".to_string(),
                    sql_names: vec!["?1".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        assert!(matches!(
            render_module(vec![&query]),
            Err(Error::MixedParameterStyles { path }) if path == PathBuf::from("src/users/sql/find.sql")
        ));
    }

    #[test]
    fn rusqlite_accepts_numbered_parameter_names() {
        let conn = rusqlite::Connection::open_in_memory().unwrap();
        let value = conn
            .query_row(
                "select ?1 + ?2",
                rusqlite::named_params! { "?1": 2_i64, "?2": 3_i64 },
                |row| row.get::<_, i64>(0),
            )
            .unwrap();

        assert_eq!(value, 5);
    }

    #[test]
    fn render_query_uses_inferred_parameter_types() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set bio = @bio where id = @id".to_string(),
            parameters: vec![
                Parameter {
                    name: "bio".to_string(),
                    sql_names: vec!["@bio".to_string()],
                    column_type: ValueType::String,
                    nullable: true,
                },
                Parameter {
                    name: "id".to_string(),
                    sql_names: vec!["@id".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query, true);

        assert!(output.contains("bio: Option<&str>"));
        assert!(output.contains("id: i64"));
        assert!(!output.contains("impl rusqlite::ToSql"));
    }

    #[test]
    fn render_query_uses_common_rust_types_for_fields_and_params() {
        let row_query = Query {
            source_path: PathBuf::from("src/files/sql/list.sql"),
            module_name: "files_sql".to_string(),
            name: "list".to_string(),
            return_type: ReturnType::Rows { row_type: None },
            sql: "select active, price, avatar, metadata, deleted from files".to_string(),
            parameters: vec![],
            columns: vec![
                Column {
                    name: "active".to_string(),
                    field_name: "active".to_string(),
                    column_type: ValueType::Bool,
                    nullable: false,
                },
                Column {
                    name: "price".to_string(),
                    field_name: "price".to_string(),
                    column_type: ValueType::F64,
                    nullable: false,
                },
                Column {
                    name: "avatar".to_string(),
                    field_name: "avatar".to_string(),
                    column_type: ValueType::Bytes,
                    nullable: false,
                },
                Column {
                    name: "metadata".to_string(),
                    field_name: "metadata".to_string(),
                    column_type: ValueType::Value,
                    nullable: false,
                },
                Column {
                    name: "deleted".to_string(),
                    field_name: "deleted".to_string(),
                    column_type: ValueType::Bool,
                    nullable: true,
                },
            ],
        };
        let execute_query = Query {
            source_path: PathBuf::from("src/files/sql/update.sql"),
            module_name: "files_sql".to_string(),
            name: "update".to_string(),
            return_type: ReturnType::Execute,
            sql: "update files set active = ?, price = ?, avatar = ?, maybe_avatar = ?".to_string(),
            parameters: vec![
                Parameter {
                    name: "active".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::Bool,
                    nullable: false,
                },
                Parameter {
                    name: "price".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::F64,
                    nullable: false,
                },
                Parameter {
                    name: "avatar".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::Bytes,
                    nullable: false,
                },
                Parameter {
                    name: "maybe_avatar".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::Bytes,
                    nullable: true,
                },
            ],
            columns: vec![],
        };

        let row_output = render_query(&row_query, true);
        let execute_output = render_query(&execute_query, true);

        assert!(row_output.contains("pub active: bool"));
        assert!(row_output.contains("pub price: f64"));
        assert!(row_output.contains("pub avatar: Vec<u8>"));
        assert!(row_output.contains("pub metadata: rusqlite::types::Value"));
        assert!(row_output.contains("pub deleted: Option<bool>"));
        assert!(execute_output.contains(
            "pub fn update(conn: &Connection, active: bool, price: f64, avatar: impl AsRef<[u8]>, maybe_avatar: Option<&[u8]>)"
        ));
        assert!(execute_output.contains("params![active, price, avatar.as_ref(), maybe_avatar]"));
    }

    #[test]
    fn render_query_preserves_sql_quotes_and_raw_string_terminators() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users_sql".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "select 'it''s fine', \"quoted\", r#\"raw\"#".to_string(),
            parameters: vec![],
            columns: vec![],
        };

        let output = render_query(&query, true);

        assert!(output.contains("r##\"select 'it''s fine', \"quoted\", r#\"raw\"#\"##"));
    }

    #[test]
    fn emit_check_reports_missing_or_changed_files_as_stale() {
        let dir = tempfile::tempdir().unwrap();
        let output = dir.path().join("src/generated/sql");
        let project = Project {
            queries: vec![Query {
                source_path: PathBuf::from("src/users/sql/list_users.sql"),
                module_name: "users_sql".to_string(),
                name: "list_users".to_string(),
                return_type: ReturnType::Rows { row_type: None },
                sql: "select id, name from users".to_string(),
                parameters: vec![],
                columns: vec![
                    Column {
                        name: "id".to_string(),
                        field_name: "id".to_string(),
                        column_type: ValueType::I64,
                        nullable: false,
                    },
                    Column {
                        name: "name".to_string(),
                        field_name: "name".to_string(),
                        column_type: ValueType::String,
                        nullable: false,
                    },
                ],
            }],
        };
        let check_config = Config {
            database: dir.path().join("app.sqlite3"),
            source_root: dir.path().join("src"),
            sql_dir: None,
            output: output.clone(),
            target: crate::config::Target::Rust,
            check: true,
        };

        assert!(matches!(
            emit(&check_config, &project),
            Err(Error::StaleGeneratedFile { .. })
        ));

        let write_config = Config {
            check: false,
            ..check_config.clone()
        };
        emit(&write_config, &project).unwrap();
        emit(&check_config, &project).unwrap();

        fs::write(output.join("users_sql.rs"), "stale").unwrap();
        assert!(matches!(
            emit(&check_config, &project),
            Err(Error::StaleGeneratedFile { .. })
        ));
    }

    #[test]
    fn render_module_rejects_duplicate_query_names() {
        let queries = vec![
            Query {
                source_path: PathBuf::from("src/users/sql/find-user.sql"),
                module_name: "users_sql".to_string(),
                name: "find_user".to_string(),
                return_type: ReturnType::Rows { row_type: None },
                sql: "select 1 as value".to_string(),
                parameters: vec![],
                columns: vec![Column {
                    name: "value".to_string(),
                    field_name: "value".to_string(),
                    column_type: ValueType::I64,
                    nullable: false,
                }],
            },
            Query {
                source_path: PathBuf::from("src/users/sql/find_user.sql"),
                module_name: "users_sql".to_string(),
                name: "find_user".to_string(),
                return_type: ReturnType::Rows { row_type: None },
                sql: "select 2 as value".to_string(),
                parameters: vec![],
                columns: vec![Column {
                    name: "value".to_string(),
                    field_name: "value".to_string(),
                    column_type: ValueType::I64,
                    nullable: false,
                }],
            },
        ];
        let query_refs = queries.iter().collect::<Vec<_>>();

        assert!(matches!(
            render_module(query_refs),
            Err(Error::DuplicateQueryNames { names }) if names == ["find_user", "find_user_one"]
        ));
    }

    #[test]
    fn render_module_rejects_scalar_helper_name_collisions() {
        let queries = vec![
            Query {
                source_path: PathBuf::from("src/users/sql/find.sql"),
                module_name: "users_sql".to_string(),
                name: "find".to_string(),
                return_type: ReturnType::Rows { row_type: None },
                sql: "select 1 as value".to_string(),
                parameters: vec![],
                columns: vec![Column {
                    name: "value".to_string(),
                    field_name: "value".to_string(),
                    column_type: ValueType::I64,
                    nullable: false,
                }],
            },
            Query {
                source_path: PathBuf::from("src/users/sql/find_one.sql"),
                module_name: "users_sql".to_string(),
                name: "find_one".to_string(),
                return_type: ReturnType::Execute,
                sql: "delete from users where id = ?".to_string(),
                parameters: vec![Parameter {
                    name: "id".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::I64,
                    nullable: false,
                }],
                columns: vec![],
            },
        ];
        let query_refs = queries.iter().collect::<Vec<_>>();

        assert!(matches!(
            render_module(query_refs),
            Err(Error::DuplicateQueryNames { names }) if names == ["find_one"]
        ));
    }

    #[test]
    fn render_module_rejects_duplicate_row_type_names() {
        let columns = vec![
            Column {
                name: "id".to_string(),
                field_name: "id".to_string(),
                column_type: ValueType::I64,
                nullable: false,
            },
            Column {
                name: "name".to_string(),
                field_name: "name".to_string(),
                column_type: ValueType::String,
                nullable: false,
            },
        ];
        let queries = vec![
            Query {
                source_path: PathBuf::from("src/orgs/sql/list_orgs.sql"),
                module_name: "orgs_sql".to_string(),
                name: "list_orgs".to_string(),
                return_type: ReturnType::Rows {
                    row_type: Some("OrgRow".to_string()),
                },
                sql: "select id, name from orgs".to_string(),
                parameters: vec![],
                columns: columns.clone(),
            },
            Query {
                source_path: PathBuf::from("src/orgs/sql/org.sql"),
                module_name: "orgs_sql".to_string(),
                name: "org".to_string(),
                return_type: ReturnType::Rows { row_type: None },
                sql: "select id, name from orgs where id = ?".to_string(),
                parameters: vec![Parameter {
                    name: "id".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::I64,
                    nullable: false,
                }],
                columns,
            },
        ];
        let query_refs = queries.iter().collect::<Vec<_>>();

        assert!(matches!(
            render_module(query_refs),
            Err(Error::DuplicateRowTypeNames { names }) if names == ["OrgRow"]
        ));
    }

    #[test]
    fn render_module_emits_shared_row_type_once() {
        let columns = vec![
            Column {
                name: "id".to_string(),
                field_name: "id".to_string(),
                column_type: ValueType::I64,
                nullable: false,
            },
            Column {
                name: "name".to_string(),
                field_name: "name".to_string(),
                column_type: ValueType::String,
                nullable: false,
            },
        ];
        let query_1 = Query {
            source_path: PathBuf::from("src/orgs/sql/find_org.sql"),
            module_name: "orgs_sql".to_string(),
            name: "find_org".to_string(),
            return_type: ReturnType::Rows {
                row_type: Some("OrgRow".to_string()),
            },
            sql: "-- returns: OrgRow\nselect id, name from orgs where id = @id".to_string(),
            parameters: vec![Parameter {
                name: "id".to_string(),
                sql_names: vec!["@id".to_string()],
                column_type: ValueType::I64,
                nullable: false,
            }],
            columns: columns.clone(),
        };
        let query_2 = Query {
            source_path: PathBuf::from("src/orgs/sql/list_orgs.sql"),
            module_name: "orgs_sql".to_string(),
            name: "list_orgs".to_string(),
            return_type: ReturnType::Rows {
                row_type: Some("OrgRow".to_string()),
            },
            sql: "-- returns: OrgRow\nselect id, name from orgs".to_string(),
            parameters: vec![],
            columns,
        };

        let output = render_module(vec![&query_1, &query_2]).unwrap();

        assert_eq!(output.matches("pub struct OrgRow").count(), 1);
        assert!(output.contains("pub fn find_org(conn: &Connection"));
        assert!(output.contains("pub fn list_orgs(conn: &Connection"));
        assert_eq!(output.matches("Result<Vec<OrgRow>>").count(), 2);
    }

    #[test]
    fn render_module_rejects_shared_row_type_mismatches() {
        let query_1 = Query {
            source_path: PathBuf::from("src/orgs/sql/find_org.sql"),
            module_name: "orgs_sql".to_string(),
            name: "find_org".to_string(),
            return_type: ReturnType::Rows {
                row_type: Some("OrgRow".to_string()),
            },
            sql: "-- returns: OrgRow\nselect id from orgs".to_string(),
            parameters: vec![],
            columns: vec![Column {
                name: "id".to_string(),
                field_name: "id".to_string(),
                column_type: ValueType::I64,
                nullable: false,
            }],
        };
        let query_2 = Query {
            source_path: PathBuf::from("src/orgs/sql/list_orgs.sql"),
            module_name: "orgs_sql".to_string(),
            name: "list_orgs".to_string(),
            return_type: ReturnType::Rows {
                row_type: Some("OrgRow".to_string()),
            },
            sql: "-- returns: OrgRow\nselect name from orgs".to_string(),
            parameters: vec![],
            columns: vec![Column {
                name: "name".to_string(),
                field_name: "name".to_string(),
                column_type: ValueType::String,
                nullable: false,
            }],
        };

        let result = render_module(vec![&query_1, &query_2]);

        let message = result.unwrap_err().to_string();

        assert!(message.contains("OrgRow"));
        assert!(message.contains("src/orgs/sql/find_org.sql"));
        assert!(message.contains("src/orgs/sql/list_orgs.sql"));
    }
}
