use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use heck::ToPascalCase;

use crate::config::Config;
use crate::error::{Error, Result};
use crate::model::{Parameter, Project, Query, ReturnType, ValueType};
use crate::sqlite::tokenize::{Token, tokenize_spans};

pub fn emit(config: &Config, project: &Project) -> Result<()> {
    let mut by_module: BTreeMap<&str, Vec<&Query>> = BTreeMap::new();
    for query in &project.queries {
        by_module.entry(&query.module_name).or_default().push(query);
    }

    fs::create_dir_all(&config.output).map_err(|source| Error::CreateDir {
        path: config.output.clone(),
        source,
    })?;

    let modules = by_module.keys().copied().collect::<Vec<_>>();
    let include_temporal = project_uses_temporal(project);
    if include_temporal && modules.contains(&"temporal") {
        return Err(Error::GeneratedTemporalModuleCollision);
    }

    for (module, queries) in by_module {
        let path = generated_module_path(&config.output, module);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|source| Error::CreateDir {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        let content = render_module(module, queries)?;
        if config.check {
            ensure_file_current(&path, &content)?;
            continue;
        }
        fs::write(&path, content).map_err(|source| Error::WriteFile {
            path: path.clone(),
            source,
        })?;
    }

    if include_temporal {
        emit_temporal_module(&config.output, config.check)?;
    }

    emit_mod_rs(&config.output, modules, include_temporal, config.check)
}

fn generated_module_path(output: &Path, module: &str) -> PathBuf {
    let mut path = output.to_path_buf();
    for segment in module.split('/') {
        path.push(segment);
    }
    path.set_extension("rs");
    path
}

fn emit_temporal_module(output: &Path, check: bool) -> Result<()> {
    fs::create_dir_all(output).map_err(|source| Error::CreateDir {
        path: output.to_path_buf(),
        source,
    })?;
    let path = output.join("temporal.rs");
    let content = render_temporal_module();
    if check {
        ensure_file_current(&path, content)?;
    } else {
        fs::write(&path, content).map_err(|source| Error::WriteFile {
            path: path.clone(),
            source,
        })?;
    }
    Ok(())
}

fn render_temporal_module() -> &'static str {
    r#"// This file is generated by Marmot. Do not edit by hand.
#![allow(dead_code)]

use std::fmt;
use std::str::FromStr;

use rusqlite::types::{FromSql, FromSqlError, FromSqlResult, ToSql, ToSqlOutput, ValueRef};

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DbDate(String);

impl DbDate {
    pub fn new(value: impl Into<String>) -> Result<Self, TemporalParseError> {
        let value = value.into();
        validate_date(&value)?;
        Ok(Self(value))
    }

    pub fn from_unchecked(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl AsRef<DbDate> for DbDate {
    fn as_ref(&self) -> &DbDate {
        self
    }
}

impl fmt::Display for DbDate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl FromStr for DbDate {
    type Err = TemporalParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::new(value)
    }
}

impl FromSql for DbDate {
    fn column_result(value: ValueRef<'_>) -> FromSqlResult<Self> {
        let value = value.as_str()?;
        Self::new(value).map_err(FromSqlError::other)
    }
}

impl ToSql for DbDate {
    fn to_sql(&self) -> rusqlite::Result<ToSqlOutput<'_>> {
        Ok(ToSqlOutput::from(self.0.as_str()))
    }
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DbDateTime(String);

impl DbDateTime {
    pub fn new(value: impl Into<String>) -> Result<Self, TemporalParseError> {
        let value = value.into();
        validate_datetime(&value)?;
        Ok(Self(value))
    }

    pub fn from_unchecked(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl AsRef<DbDateTime> for DbDateTime {
    fn as_ref(&self) -> &DbDateTime {
        self
    }
}

impl fmt::Display for DbDateTime {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl FromStr for DbDateTime {
    type Err = TemporalParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::new(value)
    }
}

impl FromSql for DbDateTime {
    fn column_result(value: ValueRef<'_>) -> FromSqlResult<Self> {
        let value = value.as_str()?;
        Self::new(value).map_err(FromSqlError::other)
    }
}

impl ToSql for DbDateTime {
    fn to_sql(&self) -> rusqlite::Result<ToSqlOutput<'_>> {
        Ok(ToSqlOutput::from(self.0.as_str()))
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TemporalParseError {
    value: String,
    expected: &'static str,
}

impl fmt::Display for TemporalParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "invalid temporal value {:?}; expected {}", self.value, self.expected)
    }
}

impl std::error::Error for TemporalParseError {}

fn validate_datetime(value: &str) -> Result<(), TemporalParseError> {
    if value.len() != 19 || value.as_bytes().get(10) != Some(&b' ') {
        return Err(temporal_error(value, "YYYY-MM-DD HH:MM:SS"));
    }
    validate_date(&value[..10]).map_err(|_| temporal_error(value, "YYYY-MM-DD HH:MM:SS"))?;
    let bytes = value.as_bytes();
    if bytes.get(13) != Some(&b':') || bytes.get(16) != Some(&b':') {
        return Err(temporal_error(value, "YYYY-MM-DD HH:MM:SS"));
    }
    let hour = parse_two_digits(value, 11, "YYYY-MM-DD HH:MM:SS")?;
    let minute = parse_two_digits(value, 14, "YYYY-MM-DD HH:MM:SS")?;
    let second = parse_two_digits(value, 17, "YYYY-MM-DD HH:MM:SS")?;
    if hour > 23 || minute > 59 || second > 59 {
        return Err(temporal_error(value, "YYYY-MM-DD HH:MM:SS"));
    }
    Ok(())
}

fn validate_date(value: &str) -> Result<(), TemporalParseError> {
    if value.len() != 10 {
        return Err(temporal_error(value, "YYYY-MM-DD"));
    }
    let bytes = value.as_bytes();
    if bytes.get(4) != Some(&b'-') || bytes.get(7) != Some(&b'-') {
        return Err(temporal_error(value, "YYYY-MM-DD"));
    }
    let year = parse_four_digits(value, 0, "YYYY-MM-DD")?;
    let month = parse_two_digits(value, 5, "YYYY-MM-DD")?;
    let day = parse_two_digits(value, 8, "YYYY-MM-DD")?;
    if month == 0 || month > 12 || day == 0 || day > days_in_month(year, month) {
        return Err(temporal_error(value, "YYYY-MM-DD"));
    }
    Ok(())
}

fn parse_four_digits(value: &str, start: usize, expected: &'static str) -> Result<u32, TemporalParseError> {
    let slice = value.get(start..start + 4).ok_or_else(|| temporal_error(value, expected))?;
    if !slice.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err(temporal_error(value, expected));
    }
    Ok(slice.parse().expect("four ASCII digits should parse as u32"))
}

fn parse_two_digits(value: &str, start: usize, expected: &'static str) -> Result<u32, TemporalParseError> {
    let slice = value.get(start..start + 2).ok_or_else(|| temporal_error(value, expected))?;
    if !slice.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err(temporal_error(value, expected));
    }
    Ok(slice.parse().expect("two ASCII digits should parse as u32"))
}

fn days_in_month(year: u32, month: u32) -> u32 {
    match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if is_leap_year(year) => 29,
        2 => 28,
        _ => 0,
    }
}

fn is_leap_year(year: u32) -> bool {
    (year % 4 == 0 && year % 100 != 0) || year % 400 == 0
}

fn temporal_error(value: &str, expected: &'static str) -> TemporalParseError {
    TemporalParseError {
        value: value.to_string(),
        expected,
    }
}
"#
}

fn emit_mod_rs(
    output: &Path,
    modules: Vec<&str>,
    include_temporal: bool,
    check: bool,
) -> Result<()> {
    let mut tree = ModuleTree::default();
    for module in modules {
        tree.insert(module);
    }
    if include_temporal {
        tree.insert("temporal");
    }
    write_module_tree(output, &tree, check)
}

#[derive(Debug, Default)]
struct ModuleTree {
    children: BTreeMap<String, ModuleTree>,
}

impl ModuleTree {
    fn insert(&mut self, module: &str) {
        let mut current = self;
        for segment in module.split('/') {
            current = current.children.entry(segment.to_string()).or_default();
        }
    }
}

fn write_module_tree(path: &Path, tree: &ModuleTree, check: bool) -> Result<()> {
    fs::create_dir_all(path).map_err(|source| Error::CreateDir {
        path: path.to_path_buf(),
        source,
    })?;
    let mod_path = path.join("mod.rs");
    let content = tree
        .children
        .keys()
        .map(|module| format!("pub mod {module};\n"))
        .collect::<String>();

    if check {
        ensure_file_current(&mod_path, &content)?;
    } else {
        fs::write(&mod_path, content).map_err(|source| Error::WriteFile {
            path: mod_path.clone(),
            source,
        })?;
    }

    for (module, child) in &tree.children {
        if !child.children.is_empty() {
            write_module_tree(&path.join(module), child, check)?;
        }
    }

    Ok(())
}

fn ensure_file_current(path: &std::path::Path, content: &str) -> Result<()> {
    match fs::read_to_string(path) {
        Ok(current) if current == content => Ok(()),
        Ok(_) => Err(Error::StaleGeneratedFile {
            path: path.to_path_buf(),
        }),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
            Err(Error::StaleGeneratedFile {
                path: path.to_path_buf(),
            })
        }
        Err(source) => Err(Error::ReadFile {
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn render_module(module: &str, queries: Vec<&Query>) -> Result<String> {
    validate_generated_names(&queries)?;
    let import_macros = render_import_macros(&queries);
    let temporal_import = if queries.iter().any(|query| query_uses_temporal(query)) {
        format!("use {} as temporal;\n", temporal_module_path(module))
    } else {
        String::new()
    };
    let mut output = format!(
        "// This file is generated by Marmot. Do not edit by hand.\n\
         #![allow(dead_code)]\n\
         use rusqlite::{{{import_macros}Connection, Result}};\n\
         {temporal_import}\n",
    );
    for query in queries {
        output.push_str(&render_query(query));
        output.push('\n');
    }

    Ok(output)
}

fn project_uses_temporal(project: &Project) -> bool {
    project.queries.iter().any(query_uses_temporal)
}

fn query_uses_temporal(query: &Query) -> bool {
    query
        .parameters
        .iter()
        .any(|param| value_type_is_temporal(&param.column_type))
        || query
            .columns
            .iter()
            .any(|column| value_type_is_temporal(&column.column_type))
}

fn value_type_is_temporal(value_type: &ValueType) -> bool {
    matches!(value_type, ValueType::DbDate | ValueType::DbDateTime)
}

fn temporal_module_path(module: &str) -> String {
    let depth = module.split('/').count();
    format!("{}temporal", "super::".repeat(depth))
}

fn validate_generated_names(queries: &[&Query]) -> Result<()> {
    let mut generated_function_names = BTreeSet::new();
    let mut duplicate_query_names = BTreeSet::new();
    for query in queries {
        for generated_name in generated_function_names_for(query) {
            if !generated_function_names.insert(generated_name.clone()) {
                duplicate_query_names.insert(generated_name);
            }
        }
    }
    if !duplicate_query_names.is_empty() {
        return Err(Error::DuplicateQueryNames {
            names: duplicate_query_names.into_iter().collect(),
        });
    }

    let mut emitted_row_types: BTreeSet<String> = BTreeSet::new();
    let mut duplicate_row_types = BTreeSet::new();

    for query in queries {
        let ReturnType::Rows = &query.return_type else {
            continue;
        };
        if query.columns.len() <= 1 {
            continue;
        }

        let row_type = format!("{}Row", query.name.to_pascal_case());

        if !emitted_row_types.insert(row_type.clone()) {
            duplicate_row_types.insert(row_type);
        }
    }

    if !duplicate_row_types.is_empty() {
        return Err(Error::DuplicateRowTypeNames {
            names: duplicate_row_types.into_iter().collect(),
        });
    }

    Ok(())
}

fn parameter_matches_positional_index(param: &Parameter, number: &str) -> bool {
    let index = numbered_parameter_index(number);
    if param
        .sql_names
        .iter()
        .any(|sql_name| !sql_name.starts_with('?'))
    {
        return false;
    }
    anonymous_parameter_slot(&param.name) == Some(index)
        || param.sql_names.iter().any(|sql_name| {
            sql_name
                .strip_prefix('?')
                .is_some_and(|number| numbered_parameter_index(number) == index)
        })
}

fn numbered_parameter_index(number: &str) -> usize {
    number.parse::<usize>().unwrap_or(0)
}

fn anonymous_parameter_slot(name: &str) -> Option<usize> {
    if name == "param" {
        return Some(1);
    }

    name.strip_prefix("param_")
        .and_then(|number| number.parse::<usize>().ok())
}

#[derive(Debug, Default)]
struct ParameterSlots {
    next_index: usize,
    named_slots: BTreeMap<String, usize>,
}

#[derive(Debug)]
struct ParameterSlot {
    index: usize,
}

impl ParameterSlots {
    fn slot(&mut self, token: &Token) -> Option<ParameterSlot> {
        match token {
            Token::ParamNamed { prefix, name } => {
                let sql_name = format!("{prefix}{name}");
                if !self.named_slots.contains_key(&sql_name) {
                    self.next_index += 1;
                    self.named_slots.insert(sql_name.clone(), self.next_index);
                }
                Some(ParameterSlot {
                    index: self.named_slots[&sql_name],
                })
            }
            Token::ParamNumbered { number } => {
                let index = numbered_parameter_index(number);
                self.next_index = self.next_index.max(index);
                Some(ParameterSlot { index })
            }
            Token::ParamAnon => {
                self.next_index += 1;
                Some(ParameterSlot {
                    index: self.next_index,
                })
            }
            _ => None,
        }
    }
}

fn generated_function_names_for(query: &Query) -> Vec<String> {
    let mut names = vec![query.name.clone()];
    if matches!(query.return_type, ReturnType::Rows) && query.columns.len() == 1 {
        names.push(format!("{}_one", query.name));
    }
    names
}

fn render_import_macros(queries: &[&Query]) -> String {
    if queries.iter().any(|query| !query.parameters.is_empty()) {
        "params, ".to_string()
    } else {
        String::new()
    }
}

fn render_query(query: &Query) -> String {
    let const_name = format!("{}_SQL", query.name.to_uppercase());
    let lowered = lower_sql_parameters(query);
    let sql = raw_string(&lowered.sql);

    let mut output = format!("const {const_name}: &str = {sql};\n\n");
    match &query.return_type {
        ReturnType::Execute => output.push_str(&render_execute(query, &lowered, &const_name)),
        ReturnType::Rows if query.columns.len() == 1 => {
            output.push_str(&render_scalar_select(query, &lowered, &const_name))
        }
        ReturnType::Rows => output.push_str(&render_select(query, &lowered, &const_name)),
    }
    output
}

fn render_select(query: &Query, lowered: &LoweredSqlParameters<'_>, const_name: &str) -> String {
    let ReturnType::Rows = &query.return_type else {
        unreachable!("render_select only accepts row queries")
    };
    let row_type = format!("{}Row", query.name.to_pascal_case());
    let fields = query
        .columns
        .iter()
        .map(|column| format!("    pub {}: {},\n", column.field_name, column.rust_type()))
        .collect::<String>();
    let params = render_params(query);
    let bindings = render_bindings(lowered);
    let row_fields = query
        .columns
        .iter()
        .enumerate()
        .map(|(index, column)| format!("            {}: row.get({index})?,\n", column.field_name))
        .collect::<String>();

    let struct_definition = format!(
        "#[derive(Debug, Clone, PartialEq)]\n\
         pub struct {row_type} {{\n{fields}}}\n\n"
    );

    format!(
        "{struct_definition}\
         pub fn {name}(conn: &Connection{params}) -> Result<Vec<{row_type}>> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             let rows = stmt.query_map({bindings}, |row| {{\n\
                 Ok({row_type} {{\n{row_fields}        }})\n\
             }})?;\n\
             rows.collect()\n\
         }}\n",
        name = query.name
    )
}

fn render_scalar_select(
    query: &Query,
    lowered: &LoweredSqlParameters<'_>,
    const_name: &str,
) -> String {
    let rust_type = query.columns[0].rust_type();
    let params = render_params(query);
    let bindings = render_bindings(lowered);
    format!(
        "pub fn {name}(conn: &Connection{params}) -> Result<Vec<{rust_type}>> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             let rows = stmt.query_map({bindings}, |row| row.get(0))?;\n\
             rows.collect()\n\
         }}\n\n\
         pub fn {name}_one(conn: &Connection{params}) -> Result<{rust_type}> {{\n\
             let mut stmt = conn.prepare_cached({const_name})?;\n\
             stmt.query_row({bindings}, |row| row.get(0))\n\
         }}\n",
        name = query.name
    )
}

fn render_execute(query: &Query, lowered: &LoweredSqlParameters<'_>, const_name: &str) -> String {
    let params = render_params(query);
    let bindings = render_bindings(lowered);
    format!(
        "pub fn {name}(conn: &Connection{params}) -> Result<usize> {{\n\
             conn.execute({const_name}, {bindings})\n\
         }}\n",
        name = query.name
    )
}

fn render_params(query: &Query) -> String {
    query
        .parameters
        .iter()
        .map(|param| format!(", {}: {}", param.name, param.rust_argument_type()))
        .collect()
}

fn render_bindings(lowered: &LoweredSqlParameters<'_>) -> String {
    if lowered.bindings.is_empty() {
        return "[]".to_string();
    }

    let names = lowered
        .bindings
        .iter()
        .map(|param| param_binding_expr(param))
        .collect::<Vec<_>>()
        .join(", ");
    format!("params![{names}]")
}

#[derive(Debug)]
struct LoweredSqlParameters<'a> {
    sql: String,
    bindings: Vec<&'a Parameter>,
}

fn lower_sql_parameters(query: &Query) -> LoweredSqlParameters<'_> {
    if query.parameters.is_empty() {
        return LoweredSqlParameters {
            sql: query.sql.clone(),
            bindings: Vec::new(),
        };
    }

    let tokens = tokenize_spans(&query.sql);
    let mut slots = ParameterSlots::default();
    let mut copied_until = 0usize;
    let mut lowered = String::with_capacity(query.sql.len());
    let mut slot_params: BTreeMap<usize, &Parameter> = BTreeMap::new();
    let mut dense_slots: BTreeMap<usize, usize> = BTreeMap::new();

    for spanned in tokens
        .iter()
        .filter(|token| is_parameter_token(&token.token))
    {
        let Some(slot) = slots.slot(&spanned.token) else {
            continue;
        };
        let param = parameter_for_slot(query, &spanned.token, slot.index, &slot_params);
        slot_params.entry(slot.index).or_insert(param);
        let next_dense_slot = dense_slots.len() + 1;
        let dense_slot = dense_slots.entry(slot.index).or_insert(next_dense_slot);

        lowered.push_str(&query.sql[copied_until..spanned.start]);
        lowered.push('?');
        lowered.push_str(&dense_slot.to_string());
        copied_until = spanned.end;
    }

    lowered.push_str(&query.sql[copied_until..]);

    let mut slots_by_dense_index = dense_slots
        .iter()
        .map(|(slot, dense)| (*dense, *slot))
        .collect::<Vec<_>>();
    slots_by_dense_index.sort_by_key(|(dense, _)| *dense);

    let bindings = slots_by_dense_index
        .into_iter()
        .map(|(_, slot)| slot)
        .map(|slot| {
            *slot_params
                .get(&slot)
                .expect("each rendered parameter slot should have a function parameter")
        })
        .collect();

    LoweredSqlParameters {
        sql: lowered,
        bindings,
    }
}

fn is_parameter_token(token: &Token) -> bool {
    matches!(
        token,
        Token::ParamAnon | Token::ParamNumbered { .. } | Token::ParamNamed { .. }
    )
}

fn parameter_for_slot<'a>(
    query: &'a Query,
    token: &Token,
    slot_index: usize,
    slot_params: &BTreeMap<usize, &'a Parameter>,
) -> &'a Parameter {
    if let Some(param) = slot_params.get(&slot_index) {
        return param;
    }

    match token {
        Token::ParamNamed { prefix, name } => {
            let sql_name = format!("{prefix}{name}");
            query
                .parameters
                .iter()
                .find(|param| param.sql_names.contains(&sql_name))
        }
        Token::ParamAnon => query
            .parameters
            .iter()
            .find(|param| {
                param.sql_names.is_empty()
                    && anonymous_parameter_slot(&param.name) == Some(slot_index)
            })
            .or_else(|| {
                query.parameters.iter().find(|param| {
                    param.sql_names.is_empty()
                        && !slot_params
                            .values()
                            .any(|bound_param| bound_param.name == param.name)
                })
            }),
        Token::ParamNumbered { number } => query.parameters.iter().find(|param| {
            param.sql_names.contains(&format!("?{number}"))
                || parameter_matches_positional_index(param, number)
        }),
        _ => None,
    }
    .expect("every SQL parameter should have a generated function parameter")
}

fn param_binding_expr(param: &crate::model::Parameter) -> String {
    if param.nullable {
        if matches!(
            param.column_type,
            crate::model::ValueType::DbDate | crate::model::ValueType::DbDateTime
        ) {
            return format!("{}.map(|value| value.as_str())", param.name);
        }
        return param.name.clone();
    }

    match param.column_type {
        crate::model::ValueType::String | crate::model::ValueType::Bytes => {
            format!("{}.as_ref()", param.name)
        }
        crate::model::ValueType::DbDate | crate::model::ValueType::DbDateTime => {
            format!("{}.as_ref().as_str()", param.name)
        }
        _ => param.name.clone(),
    }
}

fn raw_string(value: &str) -> String {
    for hashes in 0..8 {
        let marker = "#".repeat(hashes);
        let terminator = format!("\"{marker}");
        if !value.contains(&terminator) {
            return format!("r{marker}\"{value}\"{marker}");
        }
    }
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Column, Parameter, Query, ValueType};
    use std::path::PathBuf;

    #[test]
    fn render_named_params_as_positional_slots() {
        let query = Query {
            source_path: PathBuf::from("src/posts/sql/search.sql"),
            module_name: "posts".to_string(),
            name: "search".to_string(),
            return_type: ReturnType::Execute,
            sql: "update posts set viewed = 1 where user_id = @user_id and created_at >= :since and title like $pattern or owner_id = :user_id".to_string(),
            parameters: vec![
                Parameter {
                    name: "user_id".to_string(),
                    sql_names: vec!["@user_id".to_string(), ":user_id".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "since".to_string(),
                    sql_names: vec![":since".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "pattern".to_string(),
                    sql_names: vec!["$pattern".to_string()],
                    column_type: ValueType::String,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query);

        assert!(output.contains("user_id = ?1"));
        assert!(output.contains("created_at >= ?2"));
        assert!(output.contains("title like ?3"));
        assert!(output.contains("owner_id = ?4"));
        assert!(output.contains("params![user_id, since, pattern.as_ref(), user_id]"));
        assert!(!output.contains("named_params!"));
    }

    #[test]
    fn render_positional_params_uses_params_macro() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ? where id = ?".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
                Parameter {
                    name: "param_2".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query);

        assert!(output.contains("params![param.as_ref(), param_2]"));
    }

    #[test]
    fn render_dense_numbered_params_positionally() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ?2 where id = ?1 or parent_id = ?1".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec!["?1".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "param_2".to_string(),
                    sql_names: vec!["?2".to_string()],
                    column_type: ValueType::String,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query);

        assert!(output.contains("update users set name = ?1 where id = ?2 or parent_id = ?2"));
        assert!(output.contains("params![param_2.as_ref(), param]"));
    }

    #[test]
    fn render_sparse_numbered_params_as_dense_positional_params() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ?2".to_string(),
            parameters: vec![Parameter {
                name: "param_2".to_string(),
                sql_names: vec!["?2".to_string()],
                column_type: ValueType::String,
                nullable: false,
            }],
            columns: vec![],
        };

        let output = render_query(&query);

        assert!(output.contains("update users set name = ?1"));
        assert!(output.contains("params![param_2.as_ref()]"));
    }

    #[test]
    fn render_dense_mixed_numbered_and_anonymous_params_positionally() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "delete from users where id = ?1 and name = ?".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec!["?1".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
                Parameter {
                    name: "param_2".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_module("users", vec![&query]).unwrap();

        assert!(output.contains("params![param, param_2.as_ref()]"));
    }

    #[test]
    fn render_module_supports_anonymous_mixed_with_named_parameters() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ? where id = @id".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
                Parameter {
                    name: "id".to_string(),
                    sql_names: vec!["@id".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_module("users", vec![&query]).unwrap();

        assert!(output.contains("update users set name = ?1 where id = ?2"));
        assert!(output.contains("params![param.as_ref(), id]"));
    }

    #[test]
    fn render_module_supports_anonymous_mixed_with_numbered_parameters() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set name = ? where id = ?2".to_string(),
            parameters: vec![
                Parameter {
                    name: "param".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::String,
                    nullable: false,
                },
                Parameter {
                    name: "param_2".to_string(),
                    sql_names: vec!["?2".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_module("users", vec![&query]).unwrap();

        assert!(output.contains("update users set name = ?1 where id = ?2"));
        assert!(output.contains("params![param.as_ref(), param_2]"));
    }

    #[test]
    fn rusqlite_accepts_numbered_parameter_names() {
        let conn = rusqlite::Connection::open_in_memory().unwrap();
        let value = conn
            .query_row(
                "select ?1 + ?2",
                rusqlite::named_params! { "?1": 2_i64, "?2": 3_i64 },
                |row| row.get::<_, i64>(0),
            )
            .unwrap();

        assert_eq!(value, 5);
    }

    #[test]
    fn render_query_uses_inferred_parameter_types() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "update users set bio = @bio where id = @id".to_string(),
            parameters: vec![
                Parameter {
                    name: "bio".to_string(),
                    sql_names: vec!["@bio".to_string()],
                    column_type: ValueType::String,
                    nullable: true,
                },
                Parameter {
                    name: "id".to_string(),
                    sql_names: vec!["@id".to_string()],
                    column_type: ValueType::I64,
                    nullable: false,
                },
            ],
            columns: vec![],
        };

        let output = render_query(&query);

        assert!(output.contains("bio: Option<&str>"));
        assert!(output.contains("id: i64"));
        assert!(!output.contains("impl rusqlite::ToSql"));
    }

    #[test]
    fn render_query_uses_common_rust_types_for_fields_and_params() {
        let row_query = Query {
            source_path: PathBuf::from("src/files/sql/list.sql"),
            module_name: "files".to_string(),
            name: "list".to_string(),
            return_type: ReturnType::Rows,
            sql: "select active, price, avatar, metadata, deleted from files".to_string(),
            parameters: vec![],
            columns: vec![
                Column {
                    name: "active".to_string(),
                    field_name: "active".to_string(),
                    column_type: ValueType::Bool,
                    nullable: false,
                },
                Column {
                    name: "price".to_string(),
                    field_name: "price".to_string(),
                    column_type: ValueType::F64,
                    nullable: false,
                },
                Column {
                    name: "avatar".to_string(),
                    field_name: "avatar".to_string(),
                    column_type: ValueType::Bytes,
                    nullable: false,
                },
                Column {
                    name: "metadata".to_string(),
                    field_name: "metadata".to_string(),
                    column_type: ValueType::Value,
                    nullable: false,
                },
                Column {
                    name: "deleted".to_string(),
                    field_name: "deleted".to_string(),
                    column_type: ValueType::Bool,
                    nullable: true,
                },
            ],
        };
        let execute_query = Query {
            source_path: PathBuf::from("src/files/sql/update.sql"),
            module_name: "files".to_string(),
            name: "update".to_string(),
            return_type: ReturnType::Execute,
            sql: "update files set active = ?, price = ?, avatar = ?, maybe_avatar = ?".to_string(),
            parameters: vec![
                Parameter {
                    name: "active".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::Bool,
                    nullable: false,
                },
                Parameter {
                    name: "price".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::F64,
                    nullable: false,
                },
                Parameter {
                    name: "avatar".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::Bytes,
                    nullable: false,
                },
                Parameter {
                    name: "maybe_avatar".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::Bytes,
                    nullable: true,
                },
            ],
            columns: vec![],
        };

        let row_output = render_query(&row_query);
        let execute_output = render_query(&execute_query);

        assert!(row_output.contains("pub active: bool"));
        assert!(row_output.contains("pub price: f64"));
        assert!(row_output.contains("pub avatar: Vec<u8>"));
        assert!(row_output.contains("pub metadata: rusqlite::types::Value"));
        assert!(row_output.contains("pub deleted: Option<bool>"));
        assert!(execute_output.contains(
            "pub fn update(conn: &Connection, active: bool, price: f64, avatar: impl AsRef<[u8]>, maybe_avatar: Option<&[u8]>)"
        ));
        assert!(execute_output.contains("params![active, price, avatar.as_ref(), maybe_avatar]"));
    }

    #[test]
    fn render_query_preserves_sql_quotes_and_raw_string_terminators() {
        let query = Query {
            source_path: PathBuf::from("src/users/sql/find.sql"),
            module_name: "users".to_string(),
            name: "find".to_string(),
            return_type: ReturnType::Execute,
            sql: "select 'it''s fine', \"quoted\", r#\"raw\"#".to_string(),
            parameters: vec![],
            columns: vec![],
        };

        let output = render_query(&query);

        assert!(output.contains("r##\"select 'it''s fine', \"quoted\", r#\"raw\"#\"##"));
    }

    #[test]
    fn emit_check_reports_missing_or_changed_files_as_stale() {
        let dir = tempfile::tempdir().unwrap();
        let output = dir.path().join("src/generated");
        let project = Project {
            queries: vec![Query {
                source_path: PathBuf::from("src/users/sql/list_users.sql"),
                module_name: "users".to_string(),
                name: "list_users".to_string(),
                return_type: ReturnType::Rows,
                sql: "select id, name from users".to_string(),
                parameters: vec![],
                columns: vec![
                    Column {
                        name: "id".to_string(),
                        field_name: "id".to_string(),
                        column_type: ValueType::I64,
                        nullable: false,
                    },
                    Column {
                        name: "name".to_string(),
                        field_name: "name".to_string(),
                        column_type: ValueType::String,
                        nullable: false,
                    },
                ],
            }],
        };
        let check_config = Config {
            database: dir.path().join("app.sqlite3"),
            source_root: dir.path().join("src"),
            output: output.clone(),
            target: crate::config::Target::Rust,
            check: true,
            temporal: Default::default(),
        };

        assert!(matches!(
            emit(&check_config, &project),
            Err(Error::StaleGeneratedFile { .. })
        ));

        let write_config = Config {
            check: false,
            temporal: Default::default(),
            ..check_config.clone()
        };
        emit(&write_config, &project).unwrap();
        emit(&check_config, &project).unwrap();

        fs::write(output.join("users.rs"), "stale").unwrap();
        assert!(matches!(
            emit(&check_config, &project),
            Err(Error::StaleGeneratedFile { .. })
        ));
    }

    #[test]
    fn emit_rejects_root_temporal_module_when_temporal_types_are_generated() {
        let dir = tempfile::tempdir().unwrap();
        let project = Project {
            queries: vec![Query {
                source_path: PathBuf::from("src/temporal.sql"),
                module_name: "temporal".to_string(),
                name: "create_event".to_string(),
                return_type: ReturnType::Execute,
                sql: "insert into events (starts_at) values (@starts_at)".to_string(),
                parameters: vec![Parameter {
                    name: "starts_at".to_string(),
                    sql_names: vec!["@starts_at".to_string()],
                    column_type: ValueType::DbDateTime,
                    nullable: false,
                }],
                columns: vec![],
            }],
        };
        let config = Config {
            database: dir.path().join("app.sqlite3"),
            source_root: dir.path().join("src"),
            output: dir.path().join("src/generated/sql"),
            target: crate::config::Target::Rust,
            check: false,
            temporal: Default::default(),
        };

        assert!(matches!(
            emit(&config, &project),
            Err(Error::GeneratedTemporalModuleCollision)
        ));
    }

    #[test]
    fn render_module_rejects_duplicate_query_names() {
        let queries = [
            Query {
                source_path: PathBuf::from("src/users/sql/find-user.sql"),
                module_name: "users".to_string(),
                name: "find_user".to_string(),
                return_type: ReturnType::Rows,
                sql: "select 1 as value".to_string(),
                parameters: vec![],
                columns: vec![Column {
                    name: "value".to_string(),
                    field_name: "value".to_string(),
                    column_type: ValueType::I64,
                    nullable: false,
                }],
            },
            Query {
                source_path: PathBuf::from("src/users/sql/find_user.sql"),
                module_name: "users".to_string(),
                name: "find_user".to_string(),
                return_type: ReturnType::Rows,
                sql: "select 2 as value".to_string(),
                parameters: vec![],
                columns: vec![Column {
                    name: "value".to_string(),
                    field_name: "value".to_string(),
                    column_type: ValueType::I64,
                    nullable: false,
                }],
            },
        ];
        let query_refs = queries.iter().collect::<Vec<_>>();

        assert!(matches!(
            render_module("users", query_refs),
            Err(Error::DuplicateQueryNames { names }) if names == ["find_user", "find_user_one"]
        ));
    }

    #[test]
    fn render_module_rejects_scalar_helper_name_collisions() {
        let queries = [
            Query {
                source_path: PathBuf::from("src/users/sql/find.sql"),
                module_name: "users".to_string(),
                name: "find".to_string(),
                return_type: ReturnType::Rows,
                sql: "select 1 as value".to_string(),
                parameters: vec![],
                columns: vec![Column {
                    name: "value".to_string(),
                    field_name: "value".to_string(),
                    column_type: ValueType::I64,
                    nullable: false,
                }],
            },
            Query {
                source_path: PathBuf::from("src/users/sql/find_one.sql"),
                module_name: "users".to_string(),
                name: "find_one".to_string(),
                return_type: ReturnType::Execute,
                sql: "delete from users where id = ?".to_string(),
                parameters: vec![Parameter {
                    name: "id".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::I64,
                    nullable: false,
                }],
                columns: vec![],
            },
        ];
        let query_refs = queries.iter().collect::<Vec<_>>();

        assert!(matches!(
            render_module("users", query_refs),
            Err(Error::DuplicateQueryNames { names }) if names == ["find_one"]
        ));
    }

    #[test]
    fn render_module_rejects_duplicate_row_type_names() {
        let columns = vec![
            Column {
                name: "id".to_string(),
                field_name: "id".to_string(),
                column_type: ValueType::I64,
                nullable: false,
            },
            Column {
                name: "name".to_string(),
                field_name: "name".to_string(),
                column_type: ValueType::String,
                nullable: false,
            },
        ];
        let queries = [
            Query {
                source_path: PathBuf::from("src/orgs/orgs.sql"),
                module_name: "orgs".to_string(),
                name: "list_orgs".to_string(),
                return_type: ReturnType::Rows,
                sql: "select id, name from orgs".to_string(),
                parameters: vec![],
                columns: columns.clone(),
            },
            Query {
                source_path: PathBuf::from("src/orgs/orgs.sql"),
                module_name: "orgs".to_string(),
                name: "list__orgs".to_string(),
                return_type: ReturnType::Rows,
                sql: "select id, name from orgs where id = ?".to_string(),
                parameters: vec![Parameter {
                    name: "id".to_string(),
                    sql_names: vec![],
                    column_type: ValueType::I64,
                    nullable: false,
                }],
                columns,
            },
        ];
        let query_refs = queries.iter().collect::<Vec<_>>();

        assert!(matches!(
            render_module("users", query_refs),
            Err(Error::DuplicateRowTypeNames { names }) if names == ["ListOrgsRow"]
        ));
    }
}
